version: '3'

services:

  osticket:
    build: .
    image: osticket/osticket
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=0T1cket
    
      # CHANGE ME
      - INSTALL_SECRET=secret
        
      - LANGUAGE=fa

    links:
      - "mysql:database"
    ports:
      - "5335:80"
    restart: always

  mysql:
    image: mariadb
    environment:
       - MYSQL_RANDOM_ROOT_PASSWORD=true
       - MYSQL_DATABASE=osticket
       - MYSQL_USER=osticket
       - MYSQL_PASSWORD=0T1cket
    ports:
       - "3306:3306"
    restart: always
